import { defineConfig, fontProviders } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';

export default defineConfig({
  output: 'static',
  adapter: cloudflare(),
  fonts: [
    {
      name: 'Share Tech Mono',
      cssVariable: '--font-share-tech-mono',
      provider: fontProviders.fontsource(),
      weights: [400],
      styles: ['normal'],
    },
    {
      name: 'JetBrains Mono',
      cssVariable: '--font-jetbrains-mono',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'IBM Plex Mono',
      cssVariable: '--font-ibm-plex-mono',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Fira Code',
      cssVariable: '--font-fira-code',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Space Mono',
      cssVariable: '--font-space-mono',
      provider: fontProviders.fontsource(),
      weights: [400],
      styles: ['normal'],
    },
    {
      name: 'Source Code Pro',
      cssVariable: '--font-source-code-pro',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Inconsolata',
      cssVariable: '--font-inconsolata',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Roboto Mono',
      cssVariable: '--font-roboto-mono',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'PT Mono',
      cssVariable: '--font-pt-mono',
      provider: fontProviders.fontsource(),
      weights: [400],
      styles: ['normal'],
    },
    {
      name: 'Overpass Mono',
      cssVariable: '--font-overpass-mono',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Victor Mono',
      cssVariable: '--font-victor-mono',
      provider: fontProviders.fontsource(),
      weights: [400],
      styles: ['normal'],
    },
    {
      name: 'Courier Prime',
      cssVariable: '--font-courier-prime',
      provider: fontProviders.fontsource(),
      weights: [400],
      styles: ['normal'],
    },
    {
      name: 'Geist Mono',
      cssVariable: '--font-geist-mono',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Inter',
      cssVariable: '--font-inter',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Space Grotesk',
      cssVariable: '--font-space-grotesk',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'IBM Plex Sans',
      cssVariable: '--font-ibm-plex-sans',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Outfit',
      cssVariable: '--font-outfit',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'DM Sans',
      cssVariable: '--font-dm-sans',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Manrope',
      cssVariable: '--font-manrope',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
    {
      name: 'Nunito',
      cssVariable: '--font-nunito',
      provider: fontProviders.fontsource(),
      weights: [300, 400, 500],
      styles: ['normal'],
    },
  ],
});
